const lang = {
  en: {
    appName: 'My Finances',
    dashboard: 'Dashboard',
    add: '+ Add',
    history: 'History',
    fixed: 'Fixed',
    categories: 'Categories',
    admin: 'Admin',
    exit: 'Exit',
    income: 'Income',
    expenses: 'Expenses',
    balance: 'Balance',
    expensesByCategory: 'Expenses by Category',
    clickBarToFilter: 'Click a bar to filter all charts',
    weeklyOverview: 'Weekly Overview',
    dailyOverview: 'Daily Overview',
    noExpenses: 'No expenses for selected period',
    noTransactions: 'No transactions for selected period',
    addTransaction: 'Add Transaction',
    amount: 'Amount (COP)',
    category: 'Category',
    selectCategory: 'Select category...',
    date: 'Date',
    note: 'Note (optional)',
    notePlaceholder: 'Add a note...',
    saveTransaction: 'Save Transaction',
    expenseBtn: 'Expense',
    incomeBtn: 'Income',
    errorAmount: 'Enter a valid amount',
    errorCategory: 'Select a category',
    errorDate: 'Select a date',
    exportExcel: 'Export Excel',
    editCategories: 'Edit Categories',
    editCategoriesHint: 'Click any category to rename it. Click × to delete.',
    incomeCategories: 'Income Categories',
    expenseCategories: 'Expense Categories',
    newIncomeCategory: 'New income category...',
    newExpenseCategory: 'New expense category...',
    saveCategories: 'Save Categories',
    saved: 'Saved!',
    registeredUsers: 'Registered Users',
    noUsers: 'No users yet',
    loadingUsers: 'Loading users...',
    adminLabel: 'Admin',
    pinResetPending: 'PIN reset pending',
    resetPin: 'Reset PIN',
    pinResetSuccess: 'PIN Reset!',
    adminTip: "When you reset a user's PIN, they will be asked to create a new one the next time they log in.",
    enterCedula: 'Enter your cédula to continue',
    cedulaPlaceholder: 'e.g. 123456789',
    continue: 'Continue',
    checking: 'Checking...',
    welcomeBack: 'Welcome back',
    back: '← Back',
    createPin: 'Create your 4-digit PIN',
    confirmPinLabel: 'Confirm your PIN',
    next: 'Next',
    ok: 'OK',
    wrongPin: 'Wrong PIN. Try again.',
    pinMismatch: 'PINs do not match. Try again.',
    enterCedulaError: 'Enter your cédula',
    loading: 'Loading...',
    verifying: 'Verifying...',
    fixedExpenses: 'Fixed Expenses',
    fixedExpensesHint: 'Resets automatically every 1st of the month',
    totalFixed: 'Total Fixed',
    paid: 'Paid',
    pending: 'Pending',
    noFixed: 'No fixed expenses yet. Add your first one below!',
    addFixedExpense: 'Add Fixed Expense',
    namePlaceholder: 'Name (e.g. Rent)',
    amountPlaceholder: 'Amount',
    categoryPlaceholder: 'Category...',
    confirmPayment: 'Confirm Payment',
    confirmPaymentDetails: 'Confirm payment details:',
    paymentDate: 'Payment date',
    editFixed: 'Editing fixed expense:',
    defaultAmount: 'Default Amount (COP)',
    monthsSelected: 'months selected',
    done: 'Done',
    edit: 'Edit',
    save: 'Save',
    cancel: 'Cancel',
    type: 'Type',
    expenseDetailByCategory: 'Expense Detail by Category',
    clickCategoryToExpand: 'Click a category to expand',
    totalExpenses: 'Total Expenses',
    subtotal: 'Subtotal',
    transaction: 'transaction',
    transactions: 'transactions',
    months: ['January','February','March','April','May','June','July','August','September','October','November','December'],
    monthsShort: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
  },
  es: {
    appName: 'Mis Finanzas',
    dashboard: 'Inicio',
    add: '+ Agregar',
    history: 'Historial',
    fixed: 'Fijos',
    categories: 'Categorías',
    admin: 'Admin',
    exit: 'Salir',
    income: 'Ingresos',
    expenses: 'Gastos',
    balance: 'Balance',
    expensesByCategory: 'Gastos por Categoría',
    clickBarToFilter: 'Haz clic en una barra para filtrar',
    weeklyOverview: 'Resumen Semanal',
    dailyOverview: 'Resumen Diario',
    noExpenses: 'Sin gastos para el período seleccionado',
    noTransactions: 'Sin transacciones para el período seleccionado',
    addTransaction: 'Agregar Transacción',
    amount: 'Monto (COP)',
    category: 'Categoría',
    selectCategory: 'Seleccionar categoría...',
    date: 'Fecha',
    note: 'Nota (opcional)',
    notePlaceholder: 'Agregar una nota...',
    saveTransaction: 'Guardar Transacción',
    expenseBtn: 'Gasto',
    incomeBtn: 'Ingreso',
    errorAmount: 'Ingresa un monto válido',
    errorCategory: 'Selecciona una categoría',
    errorDate: 'Selecciona una fecha',
    exportExcel: 'Exportar Excel',
    editCategories: 'Editar Categorías',
    editCategoriesHint: 'Haz clic en una categoría para renombrarla. Haz clic en × para eliminarla.',
    incomeCategories: 'Categorías de Ingresos',
    expenseCategories: 'Categorías de Gastos',
    newIncomeCategory: 'Nueva categoría de ingreso...',
    newExpenseCategory: 'Nueva categoría de gasto...',
    saveCategories: 'Guardar Categorías',
    saved: '¡Guardado!',
    registeredUsers: 'Usuarios Registrados',
    noUsers: 'Aún no hay usuarios',
    loadingUsers: 'Cargando usuarios...',
    adminLabel: 'Admin',
    pinResetPending: 'Restablecimiento de PIN pendiente',
    resetPin: 'Restablecer PIN',
    pinResetSuccess: '¡PIN Restablecido!',
    adminTip: 'Al restablecer el PIN de un usuario, se le pedirá que cree uno nuevo la próxima vez que inicie sesión.',
    enterCedula: 'Ingresa tu cédula para continuar',
    cedulaPlaceholder: 'ej. 123456789',
    continue: 'Continuar',
    checking: 'Verificando...',
    welcomeBack: 'Bienvenido de nuevo',
    back: '← Volver',
    createPin: 'Crea tu PIN de 4 dígitos',
    confirmPinLabel: 'Confirma tu PIN',
    next: 'Siguiente',
    ok: 'OK',
    wrongPin: 'PIN incorrecto. Intenta de nuevo.',
    pinMismatch: 'Los PINs no coinciden. Intenta de nuevo.',
    enterCedulaError: 'Ingresa tu cédula',
    loading: 'Cargando...',
    verifying: 'Verificando...',
    fixedExpenses: 'Gastos Fijos',
    fixedExpensesHint: 'Se reinicia automáticamente el 1° de cada mes',
    totalFixed: 'Total Fijos',
    paid: 'Pagado',
    pending: 'Pendiente',
    noFixed: 'Aún no hay gastos fijos. ¡Agrega el primero abajo!',
    addFixedExpense: 'Agregar Gasto Fijo',
    namePlaceholder: 'Nombre (ej. Arriendo)',
    amountPlaceholder: 'Monto',
    categoryPlaceholder: 'Categoría...',
    confirmPayment: 'Confirmar Pago',
    confirmPaymentDetails: 'Confirma los detalles del pago:',
    paymentDate: 'Fecha de pago',
    editFixed: 'Editando gasto fijo:',
    defaultAmount: 'Monto por Defecto (COP)',
    monthsSelected: 'meses seleccionados',
    done: 'Listo',
    edit: 'Editar',
    save: 'Guardar',
    cancel: 'Cancelar',
    type: 'Tipo',
    expenseDetailByCategory: 'Detalle de Gastos por Categoría',
    clickCategoryToExpand: 'Haz clic en una categoría para expandir',
    totalExpenses: 'Total Gastos',
    subtotal: 'Subtotal',
    transaction: 'transacción',
    transactions: 'transacciones',
    months: ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
    monthsShort: ['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'],
  }
};

export default lang;
